image: registry.secoder.net/programmingcanbeverydangerous/trivialmips-document/texlive:20180824_with_make

stages:
  - build

documents:
  tags:
    - latex
  stage: build
  script:
    - make
  
  artifacts:
    paths:
      - "*.pdf"