sudo: required
language: generic
services: docker

before_install:
- docker pull aergus/latex

script:
- docker run --mount src=$TRAVIS_BUILD_DIR,target=/latex,type=bind aergus/latex /bin/sh -c "cd /latex/; make"

deploy:
  provider: releases
  api_key: $GITHUB_AUTH_TOKEN
  file_glob: true
  file: "*.pdf"
  skip_cleanup: true
  on:
    branch: master
    tags: true